"""HTML and plain-text email builder for the weekly macro briefing."""

from datetime import datetime, timedelta


def _date_range_str() -> str:
    """Return a human-readable date range string for the past week."""
    today = datetime.now()
    week_ago = today - timedelta(days=7)
    if week_ago.month == today.month:
        return f"{week_ago.strftime('%b')} {week_ago.day}\u2013{today.day}, {today.year}"
    return f"{week_ago.strftime('%b')} {week_ago.day} \u2013 {today.strftime('%b')} {today.day}, {today.year}"


def build_subject() -> str:
    return f"Weekly Macro Briefing \u2014 {_date_range_str()}"


def build_html(results: list[dict], failures: list[str]) -> str:
    """Build the full HTML email body.

    Args:
        results: list of {"country": str, "bullets": [{"text": str, "url": str}]}
        failures: list of country names that failed after retries
    """
    date_range = _date_range_str()

    country_sections = ""
    for entry in results:
        bullets_html = ""
        for b in entry["bullets"]:
            url = b.get("url", "#")
            text = b.get("text", "")
            bullets_html += (
                f'        <li style="margin-bottom:10px;line-height:1.5;">'
                f'<a href="{url}" style="color:#1a73e8;text-decoration:none;">{text}</a>'
                f"</li>\n"
            )
        country_sections += f"""
    <tr><td style="padding:20px 30px 0 30px;">
      <h2 style="margin:0 0 12px 0;font-size:20px;color:#1a1a1a;border-bottom:2px solid #e0e0e0;padding-bottom:6px;">{entry["country"]}</h2>
      <ul style="margin:0;padding-left:20px;color:#333;">
{bullets_html}      </ul>
    </td></tr>"""

    failure_section = ""
    if failures:
        names = ", ".join(failures)
        failure_section = f"""
    <tr><td style="padding:20px 30px 0 30px;">
      <p style="color:#d93025;font-size:14px;">&#9888; Data could not be retrieved for: {names}</p>
    </td></tr>"""

    return f"""\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="UTF-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#f5f5f5;font-family:Arial,Helvetica,sans-serif;">
<table role="presentation" width="100%" cellpadding="0" cellspacing="0" style="background-color:#f5f5f5;">
  <tr><td align="center" style="padding:30px 10px;">
    <table role="presentation" width="600" cellpadding="0" cellspacing="0" style="max-width:600px;background-color:#ffffff;border-radius:8px;box-shadow:0 1px 4px rgba(0,0,0,0.1);">
    <tr><td style="padding:30px 30px 0 30px;text-align:center;">
      <h1 style="margin:0 0 4px 0;font-size:26px;color:#1a1a1a;">Weekly Macro Economic Briefing</h1>
      <p style="margin:0;font-size:15px;color:#666;">{date_range}</p>
    </td></tr>
{country_sections}
{failure_section}
    <tr><td style="padding:30px;text-align:center;border-top:1px solid #e0e0e0;margin-top:20px;">
      <p style="margin:0;font-size:12px;color:#999;">Generated by Claude AI via Anthropic API</p>
    </td></tr>
    </table>
  </td></tr>
</table>
</body>
</html>"""


def build_plain_text(results: list[dict], failures: list[str]) -> str:
    """Build a plain-text version of the email."""
    date_range = _date_range_str()
    lines = [
        "Weekly Macro Economic Briefing",
        date_range,
        "=" * 40,
        "",
    ]
    for entry in results:
        lines.append(entry["country"].upper())
        lines.append("-" * len(entry["country"]))
        for b in entry["bullets"]:
            lines.append(f"  - {b.get('text', '')}  [{b.get('url', '')}]")
        lines.append("")

    if failures:
        lines.append(f"WARNING: Data could not be retrieved for: {', '.join(failures)}")
        lines.append("")

    lines.append("Generated by Claude AI via Anthropic API")
    return "\n".join(lines)
