from datetime import datetime, timedelta


def _date_range_str() -> str:
    """Return a string like 'Apr 7-13, 2026' covering the past 7 days."""
    today = datetime.utcnow().date()
    week_ago = today - timedelta(days=6)
    if week_ago.month == today.month:
        return f"{week_ago.strftime('%b')} {week_ago.day}\u2013{today.day}, {today.year}"
    return f"{week_ago.strftime('%b')} {week_ago.day} \u2013 {today.strftime('%b')} {today.day}, {today.year}"


def subject_line() -> str:
    return f"Weekly Macro Briefing \u2014 {_date_range_str()}"


def build_html(results: list[dict], failures: list[str]) -> str:
    """Build a mobile-friendly HTML email from country results.

    Parameters
    ----------
    results : list[dict]
        Each dict has "country" (str) and "bullets" (list of {"text", "url"}).
    failures : list[str]
        Country names that failed after retries.
    """
    date_range = _date_range_str()

    country_sections = ""
    for entry in results:
        bullets_html = ""
        for b in entry["bullets"]:
            url = b.get("url", "#")
            text = b.get("text", "")
            bullets_html += (
                f'<li style="margin-bottom:10px;line-height:1.5;">'
                f'<a href="{url}" style="color:#1a73e8;text-decoration:none;">{text}</a>'
                f"</li>\n"
            )
        country_sections += f"""
        <tr><td style="padding:20px 0 8px 0;">
            <h2 style="margin:0;font-size:20px;color:#1a1a1a;border-bottom:2px solid #e0e0e0;padding-bottom:6px;">
                {entry["country"]}
            </h2>
        </td></tr>
        <tr><td>
            <ul style="margin:8px 0 0 0;padding-left:20px;color:#333;">
                {bullets_html}
            </ul>
        </td></tr>
"""

    failure_section = ""
    if failures:
        names = ", ".join(failures)
        failure_section = f"""
        <tr><td style="padding:20px 0 8px 0;">
            <p style="color:#b00;font-size:14px;">
                ⚠ Could not retrieve data for: {names}
            </p>
        </td></tr>
"""

    html = f"""\
<!DOCTYPE html>
<html lang="en">
<head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1.0"></head>
<body style="margin:0;padding:0;background-color:#f5f5f5;font-family:Arial,Helvetica,sans-serif;">
<table role="presentation" width="100%" style="background-color:#f5f5f5;padding:20px 0;">
<tr><td align="center">
<table role="presentation" width="600" style="max-width:600px;background:#ffffff;border-radius:8px;overflow:hidden;">
    <!-- Header -->
    <tr><td style="background:#1a1a2e;padding:24px 30px;">
        <h1 style="margin:0;color:#ffffff;font-size:24px;font-weight:700;">Weekly Macro Economic Briefing</h1>
        <p style="margin:6px 0 0 0;color:#a0a0c0;font-size:14px;">{date_range}</p>
    </td></tr>

    <!-- Body -->
    <tr><td style="padding:10px 30px 30px 30px;">
    <table role="presentation" width="100%">
{country_sections}
{failure_section}
    </table>
    </td></tr>

    <!-- Footer -->
    <tr><td style="background:#fafafa;padding:16px 30px;border-top:1px solid #e0e0e0;">
        <p style="margin:0;font-size:12px;color:#999;">Generated by Claude AI via Anthropic API</p>
    </td></tr>
</table>
</td></tr>
</table>
</body>
</html>"""
    return html


def build_plain_text(results: list[dict], failures: list[str]) -> str:
    """Build a plain-text fallback version of the briefing."""
    date_range = _date_range_str()
    lines = [
        "WEEKLY MACRO ECONOMIC BRIEFING",
        date_range,
        "=" * 40,
        "",
    ]
    for entry in results:
        lines.append(entry["country"].upper())
        lines.append("-" * len(entry["country"]))
        for b in entry["bullets"]:
            lines.append(f"  - {b.get('text', '')}  [{b.get('url', '')}]")
        lines.append("")

    if failures:
        lines.append(f"WARNING: Could not retrieve data for: {', '.join(failures)}")
        lines.append("")

    lines.append("Generated by Claude AI via Anthropic API")
    return "\n".join(lines)
